Replace old NVIC code to fix redefinition error
The old `efm32/nvic-config.h` file has a conflicting definition for
CORE_ATOMIC_METHOD. Updating to sl_device_init_nvic eliminates this
error

```
Making all in efr32
Making all in sleepy-demo
Making all in sleepy-demo-mtd
  CC       sleepy_demo_mtd-main.o
echo MAKING examples/platforms/efr32/libopenthread-efr32mg12.a
MAKING examples/platforms/efr32/libopenthread-efr32mg12.a
(cd ../../../../../examples/platforms/efr32/ && /Library/Developer/CommandLineTools/usr/bin/make  libopenthread-efr32mg12.a )
  CC       src/libopenthread_efr32mg12_a-alarm.o
  CC       src/libopenthread_efr32mg12_a-diag.o
  CC       src/libopenthread_efr32mg12_a-entropy.o
  CC       src/libopenthread_efr32mg12_a-fem-control.o
  CC       src/libopenthread_efr32mg12_a-flash.o
  CC       src/libopenthread_efr32mg12_a-logging.o
  CC       src/libopenthread_efr32mg12_a-misc.o
  CC       src/libopenthread_efr32mg12_a-radio.o
  CC       src/libopenthread_efr32mg12_a-startup-gcc.o
  CC       src/libopenthread_efr32mg12_a-system.o
  CC       src/libopenthread_efr32mg12_a-uart.o
In file included from /Users/matran/repos/github-silabs-openthread/examples/../third_party/silabs/gecko_sdk_suite/v3.1/platform/base/hal/micro/cortexm3/efm32/efr32/nvic-config-series1-config2.h:17,
                 from /Users/matran/repos/github-silabs-openthread/examples/../third_party/silabs/gecko_sdk_suite/v3.1/platform/base/hal/micro/cortexm3/efm32/nvic-config.h:39,
                 from /Users/matran/repos/github-silabs-openthread/examples/../examples/platforms/efr32/src/system.c:180:
/Users/matran/repos/github-silabs-openthread/examples/../third_party/silabs/gecko_sdk_suite/v3.1/platform/base/hal/micro/cortexm3/efm32/config/emlib_config.h: In function 'otSysInit':
/Users/matran/repos/github-silabs-openthread/examples/../third_party/silabs/gecko_sdk_suite/v3.1/platform/base/hal/micro/cortexm3/efm32/config/emlib_config.h:20: error: "CORE_ATOMIC_METHOD" redefined [-Werror]
   20 | #define CORE_ATOMIC_METHOD    CORE_ATOMIC_METHOD_BASEPRI
      |
In file included from /Users/matran/repos/github-silabs-openthread/examples/../third_party/silabs/gecko_sdk_suite/v3.1/platform/emlib/inc/em_bus.h:34,
                 from /Users/matran/repos/github-silabs-openthread/examples/../third_party/silabs/gecko_sdk_suite/v3.1/platform/emlib/inc/em_msc.h:39,
                 from /Users/matran/repos/github-silabs-openthread/examples/../examples/platforms/efr32/src/openthread-core-efr32-config.h:36,
                 from /Users/matran/repos/github-silabs-openthread/examples/../src/core/openthread-core-config.h:46,
                 from /Users/matran/repos/github-silabs-openthread/examples/../examples/platforms/efr32/src/system.c:35:
/Users/matran/repos/github-silabs-openthread/examples/../third_party/silabs/gecko_sdk_suite/v3.1/platform/emlib/inc/em_core.h:95: note: this is the location of the previous definition
   95 | #define CORE_ATOMIC_METHOD    CORE_ATOMIC_METHOD_PRIMASK
      |
```